FROM python:3.10.2-slim-buster
WORKDIR /srv/backend
COPY backend/ ./
RUN pip install -r requirements.txt

HEALTHCHECK CMD curl --fail http://localhost:5000 || exit 1   
EXPOSE 5000
CMD [ "python", "./app.py" ]
